version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-west-2)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t grp2c2jxaimage:latest .
      - docker tag grp2c2jxaimage:latest 962804699607.dkr.ecr.us-west-2.amazonaws.com/group2c2-ecr-jxa:latest

      
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push 962804699607.dkr.ecr.us-west-2.amazonaws.com/group2c2-ecr-jxa:latest
      - echo Writing image definitions file...
      - printf '[{"name":"group2c2jxa_my_first_task","imageUri":"962804699607.dkr.ecr.us-west-2.amazonaws.com/group2c2-ecr-jxa:latest"}]' > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
